using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using UrlActionGenerator.Descriptors;

namespace UrlActionGenerator
{
    public static partial class CodeGenerator
    {
        public static void WriteUrlActions(IndentedTextWriter writer, List<AreaDescriptor> areas)
        {
            writer.WriteLines($@"// <auto-generated />
namespace Microsoft.AspNetCore.Mvc
{{
    public static partial class UrlActionGenerator_UrlHelperExtensions
    {{");

            writer.Indent += 2;
            foreach (var area in areas)
            {
                WriteAreaActions(writer, area);
            }
            writer.Indent -= 2;

            writer.WriteLines($@"
    }}
}}");
        }

        public static void WriteAreaActions(IndentedTextWriter writer, AreaDescriptor area)
        {
            CodeGenerator.WriteAreaClassStart(writer, $"{area.Name}UrlActions", $"{area.Name}Actions");

            var first = true;
            foreach (var controller in area.Controllers)
            {
                if (!first)
                    writer.WriteLineNoTabs("");
                first = false;

                WriteControllerActions(writer, controller);
            }

            CodeGenerator.WriteAreaClassEnd(writer);
        }

        public static void WriteControllerActions(IndentedTextWriter writer, ControllerDescriptor controller)
        {
            CodeGenerator.WriteHelperClassStart(writer, $"{controller.Name}ControllerActions", controller.Name);

            var first = true;
            foreach (var action in controller.Actions)
            {
                if (!first)
                    writer.WriteLineNoTabs("");
                first = false;

                WriteAction(writer, action);
            }

            CodeGenerator.WriteHelperClassEnd(writer);
        }

        public static void WriteAction(IndentedTextWriter writer, ActionDescriptor action)
        {
            writer.Write($"public string {action.Name}(");
            CodeGenerator.WriteMethodParameters(writer, action.Parameters);
            writer.WriteLine(")");

            writer.WriteLine("{");
            writer.Indent++;

            CodeGenerator.WriteRouteValues(writer, action.Parameters, new Dictionary<string, object> { ["area"] = action.Controller.Area.Name });
            writer.WriteLine($@"return urlHelper.Action(""{action.Name}"", ""{action.Controller.Name}"", __routeValues);");

            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
