//HintName: UrlActionGenerator_UrlHelperExtensions.Pages.g.cs
// <auto-generated />
namespace Microsoft.AspNetCore.Mvc
{
    public static partial class UrlActionGenerator_UrlHelperExtensions
    {
        public static UrlPages Pages(this IUrlHelper urlHelper)
            => new UrlPages(urlHelper);

        public class UrlPages
        {
            private readonly IUrlHelper urlHelper;
            public UrlPages(IUrlHelper urlHelper)
            {
                this.urlHelper = urlHelper;
            }

            public FeaturePagesFolder Feature
                => new FeaturePagesFolder(urlHelper);

            public class FeaturePagesFolder
            {
                private readonly IUrlHelper urlHelper;
                public FeaturePagesFolder(IUrlHelper urlHelper)
                {
                    this.urlHelper = urlHelper;
                }

                public string Page(int @id, int @page, int @pageSize, string @getProperty = default, string @namedGetProperty = default, string @queryParameter = default, string @namedQueryParameter = default)
                {
                    var __routeValues = Microsoft.AspNetCore.Routing.RouteValueDictionary.FromArray(new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("area", ""),
                        new System.Collections.Generic.KeyValuePair<string, object>("handler", ""),
                        new System.Collections.Generic.KeyValuePair<string, object>("id", @id),
                        new System.Collections.Generic.KeyValuePair<string, object>("page", @page),
                        new System.Collections.Generic.KeyValuePair<string, object>("pageSize", @pageSize),
                        new System.Collections.Generic.KeyValuePair<string, object>("getProperty", @getProperty),
                        new System.Collections.Generic.KeyValuePair<string, object>("namedGetProperty", @namedGetProperty),
                        new System.Collections.Generic.KeyValuePair<string, object>("queryParameter", @queryParameter),
                        new System.Collections.Generic.KeyValuePair<string, object>("namedQueryParameter", @namedQueryParameter),
                    });
                    return urlHelper.Page("/Feature/Page", __routeValues);
                }

                public string Page(int @id, string @str, string @getProperty = default, string @namedGetProperty = default, string @queryParameter = default, string @namedQueryParameter = default)
                {
                    var __routeValues = Microsoft.AspNetCore.Routing.RouteValueDictionary.FromArray(new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("area", ""),
                        new System.Collections.Generic.KeyValuePair<string, object>("handler", ""),
                        new System.Collections.Generic.KeyValuePair<string, object>("id", @id),
                        new System.Collections.Generic.KeyValuePair<string, object>("str", @str),
                        new System.Collections.Generic.KeyValuePair<string, object>("getProperty", @getProperty),
                        new System.Collections.Generic.KeyValuePair<string, object>("namedGetProperty", @namedGetProperty),
                        new System.Collections.Generic.KeyValuePair<string, object>("queryParameter", @queryParameter),
                        new System.Collections.Generic.KeyValuePair<string, object>("namedQueryParameter", @namedQueryParameter),
                    });
                    return urlHelper.Page("/Feature/Page", __routeValues);
                }

                public PagePageHandlers PageHandlers
                    => new PagePageHandlers(urlHelper);

                public class PagePageHandlers
                {
                    private readonly IUrlHelper urlHelper;
                    public PagePageHandlers(IUrlHelper urlHelper)
                    {
                        this.urlHelper = urlHelper;
                    }

                    public string Handler(int @id, string @getProperty = default, string @namedGetProperty = default, string @queryParameter = default, string @namedQueryParameter = default)
                    {
                        var __routeValues = Microsoft.AspNetCore.Routing.RouteValueDictionary.FromArray(new System.Collections.Generic.KeyValuePair<string, object>[] {
                            new System.Collections.Generic.KeyValuePair<string, object>("area", ""),
                            new System.Collections.Generic.KeyValuePair<string, object>("handler", "Handler"),
                            new System.Collections.Generic.KeyValuePair<string, object>("id", @id),
                            new System.Collections.Generic.KeyValuePair<string, object>("getProperty", @getProperty),
                            new System.Collections.Generic.KeyValuePair<string, object>("namedGetProperty", @namedGetProperty),
                            new System.Collections.Generic.KeyValuePair<string, object>("queryParameter", @queryParameter),
                            new System.Collections.Generic.KeyValuePair<string, object>("namedQueryParameter", @namedQueryParameter),
                        });
                        return urlHelper.Page("/Feature/Page", __routeValues);
                    }

                }

            }

        }

    }
}
